entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    ntfy:
      rule: "Host(`ntfy.example.com`)"
      entryPoints:
        - websecure
      service: ntfy
      tls: {}

  services:
    ntfy:
      loadBalancer:
        servers:
          - url: "http://ntfy:80"
